services:
  - type: web
    name: google-play-store-analytics
    env: python
    buildCommand: pip install -r requirements.txt && python -c "import nltk; nltk.download('vader_lexicon')"
    startCommand: gunicorn app:app -c gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0